import { AssetManager } from "../../../assetForward";

/** @type {Partial<CustomAssetDefinitionAppearance>} */
const 前发shared = {
    Random: false,
    Priority: 52,
    ParentGroup: {},
    Extended: false,
    InheritColor: "HairFront",
    Hide: ["HairFront"],
};

/** @type { CustomGroupedAssetDefinitions }} */
const assets = {
    新前发_Luzi: [
        {
            Name: "前发1",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发2",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发3",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发4",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发5",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发6",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发7",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发8",
            Left: 0,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "底", Priority: 52 },
                { Name: "高光", Priority: 52 },
            ],
        },
        {
            Name: "前发9",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发10",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发11",
            Left: 0,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "底", Priority: 52 },
                {
                    Name: "高光",
                    Priority: 52,
                },
            ],
        },
        {
            Name: "前发12",
            Left: 50,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "前", Priority: 52 },
                { Name: "后", Priority: 5 },
            ],
        },
        {
            Name: "前发13",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发14",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发15",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发16",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发17",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发18",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发19",
            Left: 50,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发20",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发21",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发22",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发23",

            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发24",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "前发25",
            Left: 0,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "底", Priority: 52 },
                { Name: "高光", Priority: 52 },
            ],
        },
        {
            Name: "前发26",
            Left: 0,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "底", Priority: 52 },
                { Name: "高光", Priority: 52 },
            ],
        },
        {
            Name: "前发27",
            Left: 0,
            Top: 0,
            ...前发shared,
            Layer: [
                { Name: "底", Priority: 52 },
                { Name: "高光", Priority: 52 },
            ],
        },
        {
            Name: "卷发1",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "卷发2",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        {
            Name: "卷发3",
            Left: 0,
            Top: 0,
            ...前发shared,
        },
        ...["前发28", "前发29", "前发30"].map((Name) => ({
            Name,
            Left: 150,
            Top: 60,
            ...前发shared,
        })),
    ],
};

/** @type { Translation.GroupedEntries } */
const translations = {
    CN: {
        新前发_Luzi: {
            前发1: "前发 1",
            前发2: "前发 2",
            前发3: "前发 3",
            前发4: "前发 4",
            前发5: "前发 5",
            前发6: "前发 6",
            前发7: "前发 7",
            前发8: "前发 8",
            前发9: "前发 9",
            前发10: "前发 10",
            前发11: "前发 11",
            前发12: "前发 12",
            前发13: "前发 13",
            前发14: "前发 14",
            前发15: "前发 15",
            前发16: "前发 16",
            前发17: "前发 17",
            前发18: "前发 18",
            前发19: "前发 19",
            前发20: "前发 20",
            前发21: "前发 21",
            前发22: "前发 22",
            前发23: "前发 23",
            前发24: "前发 24",
            前发25: "前发 25",
            前发26: "前发 26",
            前发27: "前发 27",
            卷发1: "卷发 1",
            卷发2: "卷发 2",
            卷发3: "卷发 3",
            前发28: "前发 28",
            前发29: "前发 29",
            前发30: "前发 30",
        },
    },
    EN: {
        新前发_Luzi: {
            前发1: "HairFront 1",
            前发2: "HairFront 2",
            前发3: "HairFront 3",
            前发4: "HairFront 4",
            前发5: "HairFront 5",
            前发6: "HairFront 6",
            前发7: "HairFront 7",
            前发8: "HairFront 8",
            前发9: "HairFront 9",
            前发10: "HairFront 10",
            前发11: "HairFront 11",
            前发12: "HairFront 12",
            前发13: "HairFront 13",
            前发14: "HairFront 14",
            前发15: "HairFront 15",
            前发16: "HairFront 16",
            前发17: "HairFront 17",
            前发18: "HairFront 18",
            前发19: "HairFront 19",
            前发20: "HairFront 20",
            前发21: "HairFront 21",
            前发22: "HairFront 22",
            前发23: "HairFront 23",
            前发24: "HairFront 24",
            前发25: "HairFront 25",
            前发26: "HairFront 26",
            前发27: "HairFront 27",
            卷发1: "Curly Hair 1",
            卷发2: "Curly Hair 2",
            卷发3: "Curly Hair 3",
            前发28: "Front Hair 28",
            前发29: "Front Hair 29",
            前发30: "Front Hair 30",
        },
    },
};

export default function () {
    AssetManager.addGroupedAssets(assets, translations);
}
