import { AssetManager } from "../../assetForward";
import { DialogTools } from "@mod-utils/Tools";

/** @type {CustomAssetDefinition} */
const asset = {
    Name: "拳击袋_Luzi",
    Random: false,
    Top: 0,
    Left: 0,
    AllowLock: true,
    Extended: true,
    MinOpacity: 0,
    Opacity: 0,
    SetPose: ["BackElbowTouch", "Kneel"],
    Layer: [
        { Name: "链条前", Priority: 67, Top: -800 },
        { Name: "带子", Priority: 66 },
        { Name: "链条环", Priority: 66 },
        {
            Name: "沙袋前",
            Priority: 64,
            AllowTypes: { typed: 0 },
            Alpha: [
                {
                    Group: [
                        "HairFront",
                        "HairBack",
                        "Bracelet",
                        "Cloth",
                        "ClothAccessory",
                        "ClothLower",
                        "Corset",
                        "Fluids",
                        "Garters",
                        "Gloves",
                        "HairAccessory1",
                        "HairAccessory2",
                        "HairAccessory3",
                        "Hat",
                        "ItemArms",
                        "ItemBreast",
                        "ItemButt",
                        "ItemHandheld",
                        "ItemHead",
                        "ItemHood",
                        "ItemLegs",
                        "ItemMisc",
                        "ItemNeck",
                        "ItemNose",
                        "ItemPelvis",
                        "ItemTorso",
                        "AnkletLeft",
                        "HandsLeft",
                        "Mask",
                        "Mouth",
                        "Nipples",
                        "Panties",
                        "AnkletRight",
                        "HandsRight",
                        "Shoes",
                        "Socks",
                        "SocksLeft",
                        "SocksRight",
                        "Suit",
                        "SuitLower",
                        "TailStraps",
                        "Wings",
                        "Bra",
                        "HairAccessory1",
                        "HairAccessory2",
                        "HairAccessory3",
                        "Cloth_笨笨笨蛋Luzi2",
                        "Cloth_笨笨蛋Luzi",
                        "ClothLower_笨笨笨蛋Luzi2",
                        "ClothLower_笨笨蛋Luzi",
                        "额外头发_Luzi",
                        "新后发_Luzi",
                        "新前发_Luzi",
                    ],
                    Masks: [
                        [0, -100, 500, 135], //上
                        [0, 717, 500, 120], //下
                        [0, 0, 130, 1000], //左
                        [370, 200, 135, 1000], //右
                    ],
                },
            ],
        },
        { Name: "沙袋后", Priority: 1, MinOpacity: 1 },
        { Name: "链条后", Priority: 0, Top: -800, MinOpacity: 1 },
        {
            Name: "沙袋前框",
            Priority: 65,
            AllowTypes: { typed: 1 },
            Alpha: [
                {
                    Group: [
                        "HairFront",
                        "HairBack",
                        "Bracelet",
                        "Cloth",
                        "ClothAccessory",
                        "ClothLower",
                        "Corset",
                        "Fluids",
                        "Garters",
                        "Gloves",
                        "HairAccessory1",
                        "HairAccessory2",
                        "HairAccessory3",
                        "Hat",
                        "ItemArms",
                        "ItemBreast",
                        "ItemButt",
                        "ItemHandheld",
                        "ItemHead",
                        "ItemHood",
                        "ItemLegs",
                        "ItemMisc",
                        "ItemNeck",
                        "ItemNose",
                        "ItemPelvis",
                        "ItemTorso",
                        "AnkletLeft",
                        "HandsLeft",
                        "Mask",
                        "Mouth",
                        "Nipples",
                        "Panties",
                        "AnkletRight",
                        "HandsRight",
                        "Shoes",
                        "Socks",
                        "SocksLeft",
                        "SocksRight",
                        "Suit",
                        "SuitLower",
                        "TailStraps",
                        "Wings",
                        "Bra",
                        "HairAccessory1",
                        "HairAccessory2",
                        "HairAccessory3",
                        "Cloth_笨笨笨蛋Luzi2",
                        "Cloth_笨笨蛋Luzi",
                        "ClothLower_笨笨笨蛋Luzi2",
                        "ClothLower_笨笨蛋Luzi",
                    ],
                    Masks: [
                        [0, -100, 500, 135],
                        [0, 717, 500, 120],
                        [0, 0, 130, 1000],
                        [370, 200, 135, 1000],
                    ],
                },
            ],
        },
        { Name: "照片框", Priority: 65, AllowTypes: { typed: 1 } },
        { Name: "胶带", Priority: 65, AllowTypes: { typed: 1 } },
    ],
    OverrideHeight: {
        Height: -100,
        Priority: 41,
        HeightRatioProportion: 0,
    },
};

const extended = {
    Archetype: ExtendedArchetype.TYPED,
    DrawImages: false,
    Options: [{ Name: "无照片" }, { Name: "有照片" }],
    BaselineProperty: { Opacity: 1 },
    ScriptHooks: {
        Init: PropertyOpacityInit,
        Load: PropertyOpacityLoad,
        Draw: PropertyOpacityDraw,
        Exit: PropertyOpacityExit,
    },
};

/** @type {Translation.Dialog} */
const dialog = DialogTools.replicateGroupedItemDialog(["ItemDevices"], ["拳击袋_Luzi"], {
    CN: {
        Select: "选择拳击袋配置",
        有照片: "贴上照片",
        无照片: "摘掉照片",
        Set有照片: "SourceCharacter给TargetCharacter贴上了照片",
        Set无照片: "SourceCharacter从TargetCharacter摘掉了照片",
    },
    EN: {
        Select: "Select Punching Bag Configuration",
        有照片: "Attach Photo",
        无照片: "Remove Photo",
        Set有照片: "SourceCharacter attaches a photo to TargetCharacter.",
        Set无照片: "SourceCharacter removes the photo from TargetCharacter.",
    },
    UA: {
        Select: "Виберіть конфігурацію боксерського мішка",
        有照片: "Прикріпити фотографію",
        无照片: "Зняти фотографію",
        Set有照片: "SourceCharacter прикріпили фотографію.",
        Set无照片: "SourceCharacter зняли фотографію.",
    },
    RU: {
        Select: "Выбор конфигурации боксерской груши",
        有照片: "Прикрепить фото",
        无照片: "Снять фото",
        Set有照片: "SourceCharacter прикрепил фото к DestinationCharacter.",
        Set无照片: "SourceCharacter снял фото с DestinationCharacter.",
    },
});

const translations = {
    CN: "拳击袋",
    EN: "Boxing Bag",
    UA: "Боксерський мішок",
};

export default function () {
    AssetManager.addAsset("ItemDevices", asset, extended, translations);
    AssetManager.addCustomDialog(dialog);
};
