name: Version Notification

on:
  push:
    branches:
      - release

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Remove local beta tags
        run: git tag | grep 'beta' | xargs -r git tag -d

      - name: Generate changelog info and set to output
        id: changelog
        run: |
          $CHANGELOG=$(conventional-changelog -p angular -r 1)
          echo "::set-output name=changelog::$CHANGELOG"
          $VERSION=$(git describe --tags --abbrev=0)
          echo "::set-output name=version::$VERSION"
          $NAME=$(node ./scripts/.package-props.js displayName displayName)
          echo "::set-output name=name::$NAME"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ** [${{ steps.changelog.outputs.name }}] New version released!**
            Version: ${{ steps.changelog.outputs.version }}
            ${{ steps.changelog.outputs.changelog }}
