name: Version Notification

on:
  push:
    branches:
      - release

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Remove local beta tags
        run: git tag | grep 'beta' | xargs -r git tag -d

      - name: Generate changelog info and set to output
        id: changelog
        run: |
          $CHANGELOG=$(pnpm --silent changelog:stdout -r 1)
          echo "::set-output name=changelog::$CHANGELOG"
          $VERSION=$(git describe --tags --abbrev=0)
          echo "::set-output name=version::$VERSION"
          $NAME=$(pnpm --silent package-props displayName)
          echo "::set-output name=name::$NAME"
      
      - name: Send discord message
        uses: Ilshidur/action-discord@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ** [${{ steps.changelog.outputs.name }}] New version released!**
            Version: ${{ steps.changelog.outputs.version }}
            ${{ steps.changelog.outputs.changelog }}
